name: Windows 10

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Running
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Windows@10
